version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_ratelimit
    ports:
      - "6379:6379"
  
  gateway:
    build: .
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
